name: 'Terraform Test'

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform-test:
    name: 'Terraform Test'
    runs-on: ubuntu-latest
    
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.7.0"
          terraform_wrapper: false

      - name: Terraform Init
        run: |
          cd tests
          terraform init -backend=false

      - name: Run Terraform Tests
        id: test
        run: |
          cd tests
          terraform test
        continue-on-error: false

      - name: Update PR with Test Results
        if: github.event_name == 'pull_request' && (success() || failure())
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const testOutcome = ${{ steps.test.outcome == 'success' }} ? '✅' : '❌';
            const testSummary = `### Terraform Test Results\n${testOutcome} Tests ${steps.test.outcome}\n`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: testSummary
            }); 